name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Install ShellCheck
        # https://github.com/koalaman/shellcheck/tree/v0.8.0#installing-a-pre-compiled-binary
        run: |
          scversion="v0.8.0"
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-${scversion}/shellcheck" /usr/bin/
          shellcheck --version
      - name: Checkout
        uses: actions/checkout@v2
      - name: ShellCheck
        run: shellcheck .bashrc *.sh
